#! /bin/sh
# Only for 1 monitor
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale ~/.config/background.png
${HOME}/.config/polybar/launch.sh
gentoo-pipewire-launch &
flameshot &
conky &

bspc monitor -d     

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color	"#ff00ff"
bspc config normal_border_color		"#000000"
